name: BungeeCompass
main: cymru.asheiou.bungeecompass.BungeeCompass
version: 1.0.2-SNAPSHOT
author: Asheiou
api-version: 1.17
depend:
  - SmartInvs
  - CubeCore
commands:
  beta:
    description: Open the beta features menu
    usage: /<command>
    permission: bungeecompass.beta
    permission-message: You don't have permission to participate in the betas. Donate to get access!
  givecompass:
    description: Receive a server compass
    usage: /<command>
    permission: bungeecompass.givecompass
    permission-message: You don't have bungeecompass.givecompass.
  menu:
    description: Opens the compass menu
    usage: /<command>
    permission: bungeecompass.menu
    permission-message: You don't have bungeecompass.menu.
  reloadcompass:
    description: Reloads the BungeeCompass config
    usage: /<command>
    permission: bungeecompass.reload
    permission-message: You don't have bungeecompass.reload.
permissions:
  bungeecompass.givecompass:
    description: Gives access to /givecompass
  bungeecompass.menu:
    description: Gives access to /menu
  bungeecompass.reload:
    description: Gives access to /reloadcompass